# Generated by protoc-gen-elixir with gen_descriptors=true. The descriptors are what
# grpc_reflection serves: without them it falls back to synthesizing descriptors from
# runtime metadata, and that path raises on this service's streaming RPCs — the port
# answered reflection with "Internal Server Error".
#
#   protoc --elixir_out=plugins=grpc,gen_descriptors=true,package_prefix=fleet_pulse.proto:OUT \
#     -I proto proto/fleet/v1/courier_telemetry.proto \
#     proto/common/v1/types.proto proto/common/v1/enums.proto

defmodule FleetPulse.Proto.Common.V1.OrderStatus do
  @moduledoc false

  use Protobuf,
    enum: true,
    full_name: "common.v1.OrderStatus",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.EnumDescriptorProto{
      name: "OrderStatus",
      value: [
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_UNSPECIFIED",
          number: 0,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_RECEIVED",
          number: 1,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_PACKING",
          number: 2,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_PACKED",
          number: 3,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_DISPATCHED",
          number: 4,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_IN_TRANSIT",
          number: 5,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_DELIVERED",
          number: 6,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "ORDER_STATUS_CANCELLED",
          number: 7,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      options: nil,
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :ORDER_STATUS_UNSPECIFIED, 0
  field :ORDER_STATUS_RECEIVED, 1
  field :ORDER_STATUS_PACKING, 2
  field :ORDER_STATUS_PACKED, 3
  field :ORDER_STATUS_DISPATCHED, 4
  field :ORDER_STATUS_IN_TRANSIT, 5
  field :ORDER_STATUS_DELIVERED, 6
  field :ORDER_STATUS_CANCELLED, 7
end

defmodule FleetPulse.Proto.Common.V1.CourierStatus do
  @moduledoc false

  use Protobuf,
    enum: true,
    full_name: "common.v1.CourierStatus",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.EnumDescriptorProto{
      name: "CourierStatus",
      value: [
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_UNSPECIFIED",
          number: 0,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_IDLE",
          number: 1,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_ASSIGNED",
          number: 2,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_EN_ROUTE_PICKUP",
          number: 3,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_PICKED_UP",
          number: 4,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_EN_ROUTE_DELIVERY",
          number: 5,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "COURIER_STATUS_COMPLETED",
          number: 6,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      options: nil,
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :COURIER_STATUS_UNSPECIFIED, 0
  field :COURIER_STATUS_IDLE, 1
  field :COURIER_STATUS_ASSIGNED, 2
  field :COURIER_STATUS_EN_ROUTE_PICKUP, 3
  field :COURIER_STATUS_PICKED_UP, 4
  field :COURIER_STATUS_EN_ROUTE_DELIVERY, 5
  field :COURIER_STATUS_COMPLETED, 6
end

defmodule FleetPulse.Proto.Common.V1.ReturnStatus do
  @moduledoc false

  use Protobuf,
    enum: true,
    full_name: "common.v1.ReturnStatus",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.EnumDescriptorProto{
      name: "ReturnStatus",
      value: [
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_UNSPECIFIED",
          number: 0,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_REQUESTED",
          number: 1,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_PICKED_UP_FROM_BUYER",
          number: 2,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_RECEIVED_AT_WAREHOUSE",
          number: 3,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_INSPECTED",
          number: 4,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_RESOLVED",
          number: 5,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.EnumValueDescriptorProto{
          name: "RETURN_STATUS_REJECTED",
          number: 6,
          options: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      options: nil,
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :RETURN_STATUS_UNSPECIFIED, 0
  field :RETURN_STATUS_REQUESTED, 1
  field :RETURN_STATUS_PICKED_UP_FROM_BUYER, 2
  field :RETURN_STATUS_RECEIVED_AT_WAREHOUSE, 3
  field :RETURN_STATUS_INSPECTED, 4
  field :RETURN_STATUS_RESOLVED, 5
  field :RETURN_STATUS_REJECTED, 6
end
