# Generated by protoc-gen-elixir with gen_descriptors=true.
#
# proto/shipping/v1/shipping_service.proto had existed since the service was written and these
# modules had never been generated from it, so FleetPulse.Servers.ShippingServer had no service
# to declare and could not be registered on the endpoint at all.
#
#   protoc --elixir_out=plugins=grpc,gen_descriptors=true,package_prefix=fleet_pulse.proto:OUT \
#     -I proto proto/shipping/v1/shipping_service.proto

defmodule FleetPulse.Proto.Shipping.V1.LocationCoordinates do
  @moduledoc false

  use Protobuf,
    full_name: "shipping.v1.LocationCoordinates",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.DescriptorProto{
      name: "LocationCoordinates",
      field: [
        %Google.Protobuf.FieldDescriptorProto{
          name: "latitude",
          extendee: nil,
          number: 1,
          label: :LABEL_OPTIONAL,
          type: :TYPE_DOUBLE,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "latitude",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "longitude",
          extendee: nil,
          number: 2,
          label: :LABEL_OPTIONAL,
          type: :TYPE_DOUBLE,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "longitude",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      nested_type: [],
      enum_type: [],
      extension_range: [],
      extension: [],
      options: nil,
      oneof_decl: [],
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :latitude, 1, type: :double
  field :longitude, 2, type: :double
end

defmodule FleetPulse.Proto.Shipping.V1.EstimateShippingOptionsRequest do
  @moduledoc false

  use Protobuf,
    full_name: "shipping.v1.EstimateShippingOptionsRequest",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.DescriptorProto{
      name: "EstimateShippingOptionsRequest",
      field: [
        %Google.Protobuf.FieldDescriptorProto{
          name: "origin",
          extendee: nil,
          number: 1,
          label: :LABEL_OPTIONAL,
          type: :TYPE_MESSAGE,
          type_name: ".shipping.v1.LocationCoordinates",
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "origin",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "destination",
          extendee: nil,
          number: 2,
          label: :LABEL_OPTIONAL,
          type: :TYPE_MESSAGE,
          type_name: ".shipping.v1.LocationCoordinates",
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "destination",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "total_weight_kg",
          extendee: nil,
          number: 3,
          label: :LABEL_OPTIONAL,
          type: :TYPE_DOUBLE,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "totalWeightKg",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "merchant_id",
          extendee: nil,
          number: 4,
          label: :LABEL_OPTIONAL,
          type: :TYPE_INT64,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "merchantId",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      nested_type: [],
      enum_type: [],
      extension_range: [],
      extension: [],
      options: nil,
      oneof_decl: [],
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :origin, 1, type: FleetPulse.Proto.Shipping.V1.LocationCoordinates
  field :destination, 2, type: FleetPulse.Proto.Shipping.V1.LocationCoordinates
  field :total_weight_kg, 3, type: :double, json_name: "totalWeightKg"
  field :merchant_id, 4, type: :int64, json_name: "merchantId"
end

defmodule FleetPulse.Proto.Shipping.V1.CourierOption do
  @moduledoc false

  use Protobuf,
    full_name: "shipping.v1.CourierOption",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.DescriptorProto{
      name: "CourierOption",
      field: [
        %Google.Protobuf.FieldDescriptorProto{
          name: "service_tier",
          extendee: nil,
          number: 1,
          label: :LABEL_OPTIONAL,
          type: :TYPE_STRING,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "serviceTier",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "service_name",
          extendee: nil,
          number: 2,
          label: :LABEL_OPTIONAL,
          type: :TYPE_STRING,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "serviceName",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "distance_km",
          extendee: nil,
          number: 3,
          label: :LABEL_OPTIONAL,
          type: :TYPE_DOUBLE,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "distanceKm",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "base_shipping_fee",
          extendee: nil,
          number: 4,
          label: :LABEL_OPTIONAL,
          type: :TYPE_DOUBLE,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "baseShippingFee",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "estimated_delivery_time",
          extendee: nil,
          number: 5,
          label: :LABEL_OPTIONAL,
          type: :TYPE_STRING,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "estimatedDeliveryTime",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "is_available",
          extendee: nil,
          number: 6,
          label: :LABEL_OPTIONAL,
          type: :TYPE_BOOL,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "isAvailable",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "unavailable_reason",
          extendee: nil,
          number: 7,
          label: :LABEL_OPTIONAL,
          type: :TYPE_STRING,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "unavailableReason",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      nested_type: [],
      enum_type: [],
      extension_range: [],
      extension: [],
      options: nil,
      oneof_decl: [],
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :service_tier, 1, type: :string, json_name: "serviceTier"
  field :service_name, 2, type: :string, json_name: "serviceName"
  field :distance_km, 3, type: :double, json_name: "distanceKm"
  field :base_shipping_fee, 4, type: :double, json_name: "baseShippingFee"
  field :estimated_delivery_time, 5, type: :string, json_name: "estimatedDeliveryTime"
  field :is_available, 6, type: :bool, json_name: "isAvailable"
  field :unavailable_reason, 7, type: :string, json_name: "unavailableReason"
end

defmodule FleetPulse.Proto.Shipping.V1.EstimateShippingOptionsResponse do
  @moduledoc false

  use Protobuf,
    full_name: "shipping.v1.EstimateShippingOptionsResponse",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.DescriptorProto{
      name: "EstimateShippingOptionsResponse",
      field: [
        %Google.Protobuf.FieldDescriptorProto{
          name: "distance_km",
          extendee: nil,
          number: 1,
          label: :LABEL_OPTIONAL,
          type: :TYPE_DOUBLE,
          type_name: nil,
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "distanceKm",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        },
        %Google.Protobuf.FieldDescriptorProto{
          name: "options",
          extendee: nil,
          number: 2,
          label: :LABEL_REPEATED,
          type: :TYPE_MESSAGE,
          type_name: ".shipping.v1.CourierOption",
          default_value: nil,
          options: nil,
          oneof_index: nil,
          json_name: "options",
          proto3_optional: nil,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      nested_type: [],
      enum_type: [],
      extension_range: [],
      extension: [],
      options: nil,
      oneof_decl: [],
      reserved_range: [],
      reserved_name: [],
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  field :distance_km, 1, type: :double, json_name: "distanceKm"
  field :options, 2, repeated: true, type: FleetPulse.Proto.Shipping.V1.CourierOption
end

defmodule FleetPulse.Proto.Shipping.V1.ShippingService.Service do
  @moduledoc false

  use GRPC.Service, name: "shipping.v1.ShippingService", protoc_gen_elixir_version: "0.17.0"

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.ServiceDescriptorProto{
      name: "ShippingService",
      method: [
        %Google.Protobuf.MethodDescriptorProto{
          name: "EstimateShippingOptions",
          input_type: ".shipping.v1.EstimateShippingOptionsRequest",
          output_type: ".shipping.v1.EstimateShippingOptionsResponse",
          options: nil,
          client_streaming: false,
          server_streaming: false,
          __unknown_fields__: [],
          __protobuf__: true
        }
      ],
      options: nil,
      __unknown_fields__: [],
      __protobuf__: true
    }
  end

  rpc :EstimateShippingOptions,
      FleetPulse.Proto.Shipping.V1.EstimateShippingOptionsRequest,
      FleetPulse.Proto.Shipping.V1.EstimateShippingOptionsResponse
end

defmodule FleetPulse.Proto.Shipping.V1.ShippingService.Stub do
  @moduledoc false

  use GRPC.Stub, service: FleetPulse.Proto.Shipping.V1.ShippingService.Service
end
